### ISSUE TITLE
Issues on arch

### ISSUE THREAD

**Issue by ffgomez** [quiniouben/vban#12]
Hi there,

Thanks for this fantastic idea. I am vfio'ing Win10 on my archlinux computer and one of the biggest issue is the audio, that is why i think this could be a really ellegant solution, but i cant make it work.

- I compiled and installed the vban_receptor on my linux box and i am able to run:
```
$ vban_receptor -i 192.168.192.16 -p 6980 -s KVM -b pulseaudio -d 3 -c2,41,125,7,1,45
vban_receptor version v0.8.6

Info: audio_backend_get_by_name: found backend pulseaudio
Info: audio_set_channels: setting up channels selection for 6 channels
Info: socket_open with port: 6980
```

However I cant see the streams in pavucontrol
![image](https://cloud.githubusercontent.com/assets/15813179/24579484/e1fb5644-16f6-11e7-904e-5d3f61df74fe.png)

(qemu is the sound of the VM itself, but not from the voicemeeter)

- On the VM i installed Voicemeeter and configured VBAN pointing to the linux host  in incoming and outgoing streams. They should be ok.
![image](https://cloud.githubusercontent.com/assets/15813179/24579508/7ed86b78-16f7-11e7-9d51-67b2d0272eb5.png)

I am a little bit puzzle as i cant really tell where my error is, however i think that somehow the vban_receptor is unable to communicate to pulseaudio.

Any idea about what can i check next?

Best regards and thanks in advance

**Comment by ffgomez** [comment]
the problem was the stream name... doh!

**Comment by quiniouben** [comment]
Well, happy to know you could make it work.
