### ISSUE TITLE
Emit to an Icecast server (Émettre vers un server IceCast)

### ISSUE THREAD

**Issue by LyonelB** [quiniouben/vban#17]
Serait-il possible que vban emitter puisse encoder et envoyer le signal vers un serveur Icecast ?

**Comment by quiniouben** [comment]
(french below)

Well, the very purpose of vban_emitter is to emit a local audio interface audio to a vban stream.
If you want to convert vban to / from an icecast stream, the pipe backend should be useful in conjunction with a icecast encoder / decoder command line tool (I don't know if it exists).

Le but de vban emitter est d'émettre l'audio provenant d'une interface audio locale encodé dans un flux vban.
Si vous voulez convertir vban depuis / vers icecast , le backend pipe pourrait servir en conjonction avec un encoder / decoder icecast en ligne de commande (je ne sais pas si ça existe).
