### ISSUE TITLE
Can this run as a transmitter and a receiver at the same time?

### ISSUE THREAD

**Issue by timgray** [quiniouben/vban#20]
Can I transmit audio and recieve audio at the same time  sending the line in out to the network and take a different stream in from the network and send it to the line out?  basically I am trying to send the guitar out while sending back a monitor mix.

**Comment by quiniouben** [comment]
Hi, thank you for your interest. Yes, you an do this.
Please note the following:
1- the current implementation of the emitter doesn't allow for latency tweaks ;
2- counter-intuitively, jack backend implementation is currently sub-optimal in latency ;
3- try to set the lower value possible for the -q option of vban_receptor to achieve lower latency possible ;
Hope you can however fullfill you needs.
