### ISSUE TITLE
Feature request: Mac support

### ISSUE THREAD

**Issue by SystemDisc** [quiniouben/vban#25]
If at all possible, it'd be great to be able to build and run this on macOS. I'm not sure how much work would be involved to do that.

**Comment by quiniouben** [comment]
Hi @SystemDisc , I did quick search and saw that one hypothetical way would be to use PulseAudio on OSX and compile the vban programs with pulseaudio backend.
About having a native macOS application using Core Audio, it is a bit out-of-scope of this open-source project, and you'll probably be more lucky with the [vb-audio](https://www.vb-audio.com/Voicemeeter/vban.htm) people.

**Comment by SystemDisc** [comment]
Ok, thank you!

**Comment by SystemDisc** [comment]
I started my own repo with the intention to support receiving and broadcasting audio using the VBAN protocol on all major desktop operating systems: https://github.com/SystemDisc/vban-universal

**Comment by quiniouben** [comment]
Hi, nice !
I will put this link to the wiki.

**Comment by giulianobernardi** [comment]
Hello,
Just an FYI for other that might want to try out `vban` on MacOS.

I just gave a try to use the provided `vban_emitter` and `vban_receptor` on a device running MacOS (Catalina 10.15.7).
I installed `vban` with `jack` as a backend and I managed to get the `vban_receptor` to work. As others have already mentioned in different issues, and as confirmed by the main author, the `vban_emitter` is not working (although I didn't get the usual `Fatal: Sorry jack backend is not ready for emitter yet` error all the times; sometimes I got a segmentation fault)

**Comment by dustball** [comment]
> Just an FYI for other that might want to try out `vban` on MacOS.

Which `vban` are you talking about?  The command in this github repository?  Because that one (I thought) requires ALSA which does not exist on Mac?  (I couldn't compile past the configure script's `"Missing ALSA headers"` error.) Or are you talking about the repo linked by user SystemDisc?  Or something else?
