### ISSUE TITLE
How do I select the device to emit?

### ISSUE THREAD

**Issue by Krutonium** [quiniouben/vban#26]
I am struggling to find what it wants, for -d, so far as I can tell, it wants an alsa device, but I am unsure of what to give it.

Right now it auto selects the mic on my webcam, but I need instead to select one of the HDMI outputs on my videocard. Help?

**Comment by quiniouben** [comment]
Hi @Krutonium ,
Thank you for getting interest into the project.

> I am struggling to find what it wants, for -d, so far as I can tell, it wants an alsa device, but I am unsure of what to give it.

vban_receptor expects device names as given by `aplay -L`, eg. "hdmi:CARD=PCH,DEV=0"
vban_emitter expects device names as given by `arecord -L`, eg. "front:CARD=PCH,DEV=0"

> Right now it auto selects the mic on my webcam, but I need instead to select one of the HDMI outputs on my videocard. Help?

Then, I am not too sure to understand if you are using emitter or receptor, as you mention microphone of webcam (which is an input, and can be used by emitter) and HDMI output of videocard (which can be used by receptor). I would guess for the receptor, as I don't know about any computer with input on HDMI connection. Therefore, give a try at `aplay -L` to know what are the available devices.

**Comment by Krutonium** [comment]
Well what I am trying to do is forward the desktop audio of my Linux machine to Windows, right? I assumed that emitter was the correct way to do that, since... emit. But I guess based on what you said, the correct way to do it is receptor?

**Comment by quiniouben** [comment]
Hi
> Well what I am trying to do is forward the desktop audio of my Linux machine to Windows, right? I assumed that emitter was the correct way to do that, since... emit. But I guess based on what you said, the correct way to do it is receptor?

No, you are right, if you want to emit, use an emitter :).
My explanations above stand for Alsa backend and you cannot simply achieve what you want with alsa.
If you want to forward all your audio (including software sources), you should be successful with using pulseaudio backend + ensuring PulseAudio settings are correct.

**Explanation**
- when you launch vban_emitter with `-bpulseaudio` option, it will create a recording stream and register to the pulseaudio server.
- in pavucontrol (the control gui for pulseaudio), you should be then able to setup the "record from" source of this stream (it is named "vban") and select the "Monitor of XXX" where XXX is the main output of your linux machine. Eg: "Monitor of built-in Audio Digital Stereo (HDMI)".

**Illustration**
`vban_emitter -i 192.168.1.1 -p6789 -sStream -bpulseaudio -r48000`

![pavucontrol_vban](https://user-images.githubusercontent.com/13813735/46374967-6c578500-c692-11e8-8e5a-6a425a28e37b.png)

**Comment by Krutonium** [comment]
Thanks!

**Comment by ToxMox** [comment]
Hi there. I'm trying to do something similar. I've got audio out from my Pi via vban_emitter working using the Pulseaudio instructions above. 
I'd also like to at the same time bring my mic audio from my PC into my Pi as a mic input using vban_receptor (and Pulseaudio) but I'm not sure how to configure it or if it is possible.

Any insights would be greatly appreciated :)

**Comment by webdev778** [comment]
awesome, Appreciate you a lot @quiniouben , it works as charm
