### ISSUE TITLE
please add for newbies in the readme to add those libraries

### ISSUE THREAD

**Issue by allegfede** [quiniouben/vban#32]
i miss in my raspberry:
automake

In my i7 i miss indeed:
libjack-jackd2-dev

**Comment by TurtleForGaming** [comment]
Well its more libjack*dev libpulse*dev and libasound*dev since I din't figured out how to diable a backend in the compilation process

**Comment by quiniouben** [comment]
I will try to update the readme soon about these.
About disabling backends when compiling, you should be able to do so at `./configure` step.
To know how to do, you could invoke `./configure --help`. You will get some generic help instructions and a part like this:
`
Optional Features:
  --disable-option-checking  ignore unrecognized --enable/--with options
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --enable-silent-rules   less verbose build output (undo: "make V=1")
  --disable-silent-rules  verbose build output (undo: "make V=0")
  --enable-dependency-tracking
                          do not reject slow dependency extractors
  --disable-dependency-tracking
                          speeds up one-time build
  --enable-alsa    Turn on alsa backend
  --enable-pulseaudio    Turn on pulseaudio backend
  --enable-jack    Turn on jack backend
`

So, to disable the compilation of let's say jack backend, you can invoke configure like this:
`./configure --disable-jack`

Hope this helps

**Comment by NeroBurner** [comment]
I think this issue is fixed in the current README
