### ISSUE TITLE
Can't enable stream

### ISSUE THREAD

**Issue by TrickShotMLG02** [quiniouben/vban#35]
I have installed your Webpanel. When i add a new server and press start, nothing happens.

**Comment by TrickShotMLG02** [comment]
Also when i start vban emitter with the cmd line nothing happens

**Comment by quiniouben** [comment]
Hi, thank you for your interest and report.
The webpanel you mention is probably the VBAN-manager project, which I didn't participate to.
About the command line invocation, could you give more details:

- which options ?
- can you try again with -l3 option ?
- what is your system (distribution, cpu hardware, audio hardware ... ) ?

**Comment by quiniouben** [comment]
Any news ?

**Comment by TrickShotMLG02** [comment]
No, but I gave up 😂
