### ISSUE TITLE
unable to run configure

### ISSUE THREAD

**Issue by Murkur** [quiniouben/vban#42]
unable to run configure as it fails with exit 77
[config.log](https://github.com/quiniouben/vban/files/4084323/config.log)

**Comment by NeroBurner** [comment]
shameless self promotion: wanna try with the cmake version?

**Comment by quiniouben** [comment]
The error is strange. The first idea that come to my mind leads to the question: Is it possible that you run autogen.sh at least once, then some update of your distribution occured and then you didn't run autogen.sh again ?
About using the cmake version, please feel free ! I am about to take a look at next ticket :).

**Comment by Murkur** [comment]
ill take a look at the cmake version in a few days as the PC I was running this on had a failed battery which im waiting for a new one to arrive and it refuses to operate on AC utility

**Comment by SteveClement** [comment]
@Murkur those more exotic messages can sometimes also be because of badly set environment variables.
(Like if you have a .shellrc file that is bloated) One try would be to just use another, simpler no customizations, shell.

**Comment by Murkur** [comment]
forgot to close this as the Cmake version was fuctional
