### ISSUE TITLE
type-limits warning in audio.c

### ISSUE THREAD

**Issue by NeroBurner** [quiniouben/vban#44]
```
/home/nero/repos/vban/src/common/audio.c: In function ‘audio_read’:
/home/nero/repos/vban/src/common/audio.c:261:14: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
  261 |     if (size < 0)
      |              ^
```

edit: github link
https://github.com/quiniouben/vban/blob/a2aaf016a67a4a31e2d0aa53eb6833f34154e92e/src/common/audio.c#L260-L265

**Comment by quiniouben** [comment]
Hi @NeroBurner , thanks, this is fixed.

**Comment by NeroBurner** [comment]
fixed in https://github.com/quiniouben/vban/commit/03606e69c68974208539b40f8c4411ef96a4c9de
just for future reference
