### ISSUE TITLE
Let CMake be more strict?

### ISSUE THREAD

**Issue by NeroBurner** [quiniouben/vban#45]
the cmake build script I wrote has all the backends enabled, but still works if the dependencies for the backends are missing. A backend can be disabled with the `-DDISABLE_<BACKEND>=Yes` configuration flag.

I don't like this fallback behavior. I'd rather have `-DWITH_ALSA=Yes` and fail with an error if alsa was not found. Per default I would enable all the backends and let the user disable them one by one and have the user have an active decision.

@quiniouben how does the autotools build system handle missing dependencies? With fallback or strict?

**Comment by quiniouben** [comment]
> @quiniouben how does the autotools build system handle missing dependencies? With fallback or strict?
It is strict, and I would also prefer that cmake behaves so.
