### ISSUE TITLE
Question: How to control volume?

### ISSUE THREAD

**Issue by jtabb16** [quiniouben/vban#53]
Hey. This looks like a cool project. I read through some of the source code, but didn't see where you could set the volume of the emitter. Is it possible to control the volume in the command line with these tools?

**Comment by NeroBurner** [comment]
I thin the scope of vban is to just send and receive the raw input.

You could use pavuctl to manipulate the input/output. If you're using pulseaudio

**Comment by quiniouben** [comment]
Hi @jtabb16 , as @NeroBurner mentions it, vban is only a raw audio transport protocol. Everything else is up to the surrounding infrastructure. However, if you use this in conjunction with [voicemeeter](https://www.vb-audio.com/Voicemeeter/index.htm) , you could make use of the included vban_sendtext utility to remote control parameters, including volume of voicemeeter tracks

**Comment by QuantumFluxCapacitor** [comment]
Hi, is there a way to link the volume control buttons in raspbian to the stream output?

Voicemeeter in windows can't do this either, Only to the voicemeeter input.

**Comment by quiniouben** [comment]
Hi @QuantumFluxCapacitor , I guess I can only repeat my previous answer: basically no., vban open source project is about transporting bare audio.

**Comment by QuantumFluxCapacitor** [comment]
> 
> 
> Hi @QuantumFluxCapacitor , I guess I can only repeat my previous answer: basically no., vban open source project is about transporting bare audio.

Yes I understood that, but hooking the volume keys to output A is not a problem, and to output B is?
