### ISSUE TITLE
Newbie install problem.

### ISSUE THREAD

**Issue by Francesco-Rugg** [quiniouben/vban#54]
Hi all, I have a problem related to the installation of the program.

Regarding the README file I install on my RPI 
all the audio library  in the list with this code
`sudo apt-get install libasound-dev`
`sudo apt-get install libpulse-dev`
`sudo apt-get install libjack-dev`
 
after I run an update with `sudo apt-get update` and the install 
autoconf and automake with 
`sudo apt-get install autoconf`
`sudo apt-get install automake`

Now what I have to do? (I'm really new with the installation of a program with github and raspberry also with terminal). Can somebody explain to me all the installation process

**Comment by amitdvir1122** [comment]
Sure! 
Here are all the commands I used to install the program:
`git clone https://github.com/quiniouben/vban.git`
`cd vban`
`./autogen.sh`
`./configure`
`make`
`make install`
If you encounter any errors my best tip for you is to search them online :)
If you don't/ not sure you have git do:
`sudo apt-get update`
 `sudo apt-get install git`

**Comment by Francesco-Rugg** [comment]
@amitdvir1122  , thank you so much. 
Now that I have install the program how I have to "invoke" for example vban_receptor?

**Comment by Francesco-Rugg** [comment]
Ok, now works, I had a problem during the installation. I had to add `sudo make install` and now I can invoke vban.
Thanks all

**Comment by amitdvir1122** [comment]
No problem <3
