### ISSUE TITLE
vban_emitter error in raspbian

### ISSUE THREAD

**Issue by QuantumFluxCapacitor** [quiniouben/vban#56]
Hi, I am trying to setup a vban emitter to vban receptor stream, and the receptor works fine but when I start vban emitter i get the following error (no matter which options i use):

pi@raspberrypi:~/Documents/vban-master $ vban_emitter --ipaddress=10.19.71.2 --port=4464 --streamname=x
vban_emitter version 2.1.0

Fatal: alsa_open: open error: No such file or directory
Error: audio_set_stream_config: could not open backend with new config

arecord -Dsysdefault -r48000 -c1 -fs16_LE test.wav
arecord: main:828: audio open error: No such file or directory

aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dmix:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=2
    bcm2835 ALSA, bcm2835 IEC958/HDMI1
    Hardware device with all software conversions

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

the ./configure part I used --enable-alsa --disable-pulseaudio --disable-jack 
before compiling.

This is on raspbian buster but this problem also popped up in stretch and on both an Rpi 3B+ and an Rpi 4.

I hope you can help me on this one. Thanks in advance!

**Comment by quiniouben** [comment]
Hi, that arecord reports the same error than vban_emitter is a good hint that the ALSA "default" input device is not properly working / configured. I would run
`$ arecord -L`
to know what are the input devices (aplay gives the output ones), and try to use one of them explicitely, eg:
> pi@raspberrypi:~/Documents/vban-master $ vban_emitter --ipaddress=10.19.71.2 --port=4464 --streamname=x --device="hw:CARD=ALSA,DEV=0"

**Comment by QuantumFluxCapacitor** [comment]
I got the app to run. It worked fine, even with kodi (After I configured vban_emitter for pulseaudio)

But now I get the same fatal error when I start vban_emitter as a systemd service. It exists immediately, or restarts indefinitely.
To recap: From a shell i can start vban_emitter manually, which works fine. When started as a service, it gives the same error I reported initially.

**Comment by QuantumFluxCapacitor** [comment]
Please close this issue. I will rephrase the issue with vban as a service in a new issue report.
