### ISSUE TITLE
Propose a web / gui interface to the software

### ISSUE THREAD

**Issue by quiniouben** [quiniouben/vban#7]
vban_receptor is a command line tool that could be enhanced by a gui, would it be web or something else.

**Comment by erikvanhamme** [comment]
Making a Qt app to control vban_receptor and its arguments is not that hard. But...

If you want to include the tone controls and VU meters as seen in the official VBAN Receptor app, it will require more work, specifically you would need to have the Qt app receive the packets and play them back through the Qt sound system. Implementing the tone controls is quite easy. You could use Equalizer APO's BiQuad class as written by Jonas Thedering to implement the low and high-shelf filters.

Just my 2c ;)

**Comment by quiniouben** [comment]
Sure, I think you grasped all of it.
If you have the will and the time to work on this, don't hesitate ;).

**Comment by EmerickH** [comment]
Hello,
I made it!
https://github.com/EmerickH/VBAN-manager
It still in developpement but well working for me.

Emerick

**Comment by quiniouben** [comment]
Hello,
Nice !
I will definitively take a look asap.
Thank's a lot for your effort and my apologize for the slow reaction

**Comment by quiniouben** [comment]
It took me again a long while but I gave it a quick test: nice !
At least there is some sort of gui for the command line tools.
Thank you.
Would you like that we add some link in the README of this project to yours ?

**Comment by EmerickH** [comment]
@quiniouben Thank you and of course you can if you want!

**Comment by quiniouben** [comment]
I added a link to VBAN-manager in the README.md
