### ISSUE TITLE
Whitenoise issue

### ISSUE THREAD

**Issue by Sm0rezDev** [quiniouben/vban#78]
Getting a very noisy(white noise + actual audio) audio at the end with vban_emitter.

**Comment by Sm0rezDev** [comment]
wasnt vban issue.

**Comment by NeroBurner** [comment]
@Sm0rezDev could you please explain for future reference what caused the issue? Maybe someone in the future stumbles upon your thread and thinks "what did you see?!" 

https://xkcd.com/979/

**Comment by Sm0rezDev** [comment]
Ok. Here's what I did to fix some of the noise 

1. Reduce the sampling rate from e.x 48000 Hz to 44000 or 32000 Hz

2. (The one that fixed my problem) Reinstalled the OS, you could get away by reinstalling the audio backend like Alsa.

**Comment by NeroBurner** [comment]
Thank you for taking the time to write this clarifying response :bow:
